### PR TITLE
Add papermill init test case

### PR DESCRIPTION
**Pull request by Jeffwan**
*Issue #, if available:*
#78 

*Description of changes:*
Add a presubmit job to test notebooks using papermill. Only 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jeffwan** [comment]
image

**Comment by Jeffwan** [comment]
```

Executing:   0%|          | 0/5 [00:00<?, ?cell/s]/usr/local/lib/python3.6/dist-packages/IPython/paths.py:67: UserWarning: IPython parent '/home/jovyan' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
/usr/local/lib/python3.6/dist-packages/IPython/paths.py:67: UserWarning: IPython parent '/home/jovyan' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))

Executing:  20%|██        | 1/5 [00:00<00:03,  1.32cell/s]
Executing:  60%|██████    | 3/5 [02:22<00:43, 21.74s/cell]
Executing:  80%|████████  | 4/5 [02:23<00:15, 15.47s/cell]
Executing: 100%|██████████| 5/5 [02:23<00:00, 11.07s/cell]
Executing: 100%|██████████| 5/5 [02:25<00:00, 29.04s/cell]
```

test runs pretty well

**Comment by PatrickXYS** [comment]
Let me know if you need lgtm to merge

**Comment by Jeffwan** [comment]
@PatrickXYS 
Let's merge it

**Pull request merged**
