### PR TITLE
fixing bug with kfp samgemaker notebook

### PR DESCRIPTION
**Pull request by dalbhanj**
*Issue #, if available:*https://github.com/aws-samples/eks-kubeflow-workshop/issues/70

*Description of changes:* I was getting an error while executing kfp run with Sagemaker notebook. Its possible that the latest kfp sdk has breaking changes that affects this run. Pinning to specific kfp version (v0.1.29) fixes the issue

See https://github.com/aws-samples/eks-kubeflow-workshop/issues/70 for more details

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Jeffwan** [comment]
Not sure why there's so many diffs. Checked notebooks and it looks good to me.

**Comment by Jeffwan** [comment]
Not sure why there's so many diffs. Checked notebooks and it looks good to me.

**Comment by Jeffwan** [comment]
Thanks @dalbhanj for the fix

**Comment by swarnaditya** [comment]
make_bucket failed: s3://qhg411-kubeflow-pipeline-data An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

facing this error while creating an S3 bucket to store pipeline data

**Comment by dalbhanj** [comment]
@swarnaditya can you please open new issues on EKS workshop (https://github.com/aws-samples/eks-workshop/issues)? We inherit some permissions from Fairing chapter (where we apply S3 permissions) into this chapter (https://www.eksworkshop.com/advanced/420_kubeflow/fairing/#assign-s3-and-ecr-permissions).

**Comment by swarnaditya** [comment]
checked both are AmazonS3FullAccess & AmazonEC2ContainerRegistryFullAccess both permission are there.

**Comment by dalbhanj** [comment]
Can you create an issue on eksworkshop and tag me?

**Pull request merged**
